[package]
name = "tangram_pool"

description = { workspace = true }
edition = { workspace = true }
homepage = { workspace = true }
license = { workspace = true }
publish = false
repository = { workspace = true }
version = { workspace = true }

[lints]
workspace = true

[dependencies]
tokio = { workspace = true }
