def object_id(input: str) -> str: ...
def normalize_object(input: str) -> str: ...
def parse_value(input: str) -> str: ...
def stringify_value(input: str) -> str: ...
def checksum(input: bytes, algorithm: str) -> str: ...
