pub(super) enum Request {
	DeleteArchiveQueueEntry(crate::archive::queue::delete::Arg),
	DeleteIndexQueueFragment(crate::index::queue::delete::Arg),
	DeleteLog(crate::log::delete::Arg),
	DeleteObject(super::delete::Request),
	DeleteObjectBatch(Vec<super::delete::Request>),
	DeleteObjectCacheEntry(crate::object::cache::delete::Arg),
	PutArchiveQueueEntry(crate::archive::queue::put::Arg),
	PutIndexQueueFragment(crate::index::queue::put::Arg),
	PutLogBatch(Vec<crate::log::put::Arg>),
	PutLogEnd(crate::log::end::Arg),
	PutObject(super::put::Request),
	PutObjectBatch(Vec<super::put::Request>),
	PutObjectCacheEntry(crate::object::cache::put::Arg),
	PutObjectCacheEntryWithObject(crate::object::cache::put::object::Arg),
}
