pub(super) enum Request {
	DeleteIndexer(crate::indexer::delete::Arg),
	DeleteLog(crate::log::delete::Arg),
	DeleteObject(super::delete::Request),
	DeleteObjectArchiveQueueEntry(crate::object::archive::queue::delete::Arg),
	DeleteObjectBatch(Vec<super::delete::Request>),
	DeleteObjectCacheEntry(crate::object::cache::delete::Arg),
	DeleteObjectIndexQueueFragment(crate::object::index::queue::delete::Arg),
	PutLogBatch(Vec<crate::log::put::Arg>),
	PutIndexer(crate::indexer::put::Arg),
	PutObject(super::put::Request),
	PutObjectArchiveQueueEntry(crate::object::archive::queue::put::Arg),
	PutObjectBatch(Vec<super::put::Request>),
	PutObjectCacheEntry(crate::object::cache::put::Arg),
	PutObjectCacheEntryWithObject(crate::object::cache::put::object::Arg),
	PutObjectIndexQueueFragment(crate::object::index::queue::put::Arg),
	UpdateIndexer(crate::indexer::update::Arg),
}
