[package]
name = "tangram_module"

description = { workspace = true }
edition = { workspace = true }
homepage = { workspace = true }
license = { workspace = true }
publish = false
repository = { workspace = true }
rust-version = { workspace = true }
version = { workspace = true }

[lints]
workspace = true

[build-dependencies]
glob = { workspace = true }
scopeguard = { workspace = true }

[dependencies]
dashmap = { workspace = true }
fnv = { workspace = true }
include_dir = { workspace = true }
indoc = { workspace = true }
oxc = { workspace = true }
oxc_formatter = { workspace = true }
tangram_client = { workspace = true }
tangram_either = { workspace = true }
tangram_util = { workspace = true }
tokio = { workspace = true }
