[package]
name = "tangram_runtime"

description = { workspace = true }
edition = { workspace = true }
homepage = { workspace = true }
license = { workspace = true }
publish = false
repository = { workspace = true }
version = { workspace = true }

[lints]
workspace = true

[build-dependencies]
v8 = { workspace = true }

[dependencies]
base64 = { workspace = true }
bytes = { workspace = true }
derive_more = { workspace = true }
either = { workspace = true }
futures = { workspace = true }
hex = { workspace = true }
indoc = { workspace = true }
itertools = { workspace = true }
libc = { workspace = true }
lsp-types = { workspace = true }
num = { workspace = true }
reqwest = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
toml = { workspace = true }
serde_v8 = { workspace = true }
serde_yaml = { workspace = true }
sourcemap = { workspace = true }
tangram_client = { workspace = true }
tangram_error = { workspace = true }
tangram_language = { workspace = true }
tangram_package = { workspace = true }
tempfile = { workspace = true }
tokio = { workspace = true }
tokio-util = { workspace = true }
tracing = { workspace = true }
url = { workspace = true }
v8 = { workspace = true }
