[build]
rustflags = ["-Zthreads=8"]
target-applies-to-host = false

[host]
rustflags = ["-Zthreads=8"]

[target.aarch64-unknown-linux-gnu]
rustflags = ["-Zthreads=8", "-C", "target-feature=+crt-static"]

[env]
RUSTY_V8_MIRROR = "https://github.com/denoland/rusty_v8/releases/download"

[profile.dev]
debug = "line-tables-only"

[profile.dev.package."*"]
debug = false

[profile.dev.package.blake3]
opt-level = 3
overflow-checks = false

[profile.debugger]
inherits = "dev"
debug = true

[resolver]
feature-unification = "workspace"

[unstable]
feature-unification = true
host-config = true
target-applies-to-host = true
