apiVersion: v1
kind: Service
metadata:
  name: postgres
spec:
  type: LoadBalancer
  selector:
    app: postgres
  ports:
    - port: 5432
      targetPort: 5432
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
  labels:
    app: postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
        - name: postgres
          image: postgres:18.1
          env:
            - name: POSTGRES_HOST_AUTH_METHOD
              value: trust
          ports:
            - containerPort: 5432
          readinessProbe:
            exec:
              command:
                - pg_isready
                - -U
                - postgres
            initialDelaySeconds: 1
            periodSeconds: 1
            timeoutSeconds: 5
            failureThreshold: 10
---
apiVersion: v1
kind: Service
metadata:
  name: scylla
spec:
  type: LoadBalancer
  selector:
    app: scylla
  ports:
    - port: 9042
      targetPort: 9042
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: scylla
  labels:
    app: scylla
spec:
  replicas: 1
  selector:
    matchLabels:
      app: scylla
  template:
    metadata:
      labels:
        app: scylla
    spec:
      containers:
        - name: scylla
          image: scylladb/scylla:2025.4
          args:
            - --overprovisioned
            - "1"
          ports:
            - containerPort: 9042
          readinessProbe:
            exec:
              command:
                - cqlsh
                - -e
                - DESC KEYSPACES
            initialDelaySeconds: 5
            periodSeconds: 1
            timeoutSeconds: 5
            failureThreshold: 60
---
apiVersion: v1
kind: Service
metadata:
  name: nats
spec:
  type: LoadBalancer
  selector:
    app: nats
  ports:
    - name: client
      port: 4222
      targetPort: 4222
    - name: management
      port: 8222
      targetPort: 8222
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nats
  labels:
    app: nats
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nats
  template:
    metadata:
      labels:
        app: nats
    spec:
      containers:
        - name: nats
          image: nats:2.12.3
          args:
            - --jetstream
          ports:
            - containerPort: 4222
            - containerPort: 8222
          readinessProbe:
            tcpSocket:
              port: 4222
            initialDelaySeconds: 1
            periodSeconds: 1
            timeoutSeconds: 5
            failureThreshold: 10
---
apiVersion: v1
kind: Service
metadata:
  name: fdb
spec:
  type: LoadBalancer
  selector:
    app: fdb
  ports:
    - port: 4500
      targetPort: 4500
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: fdb
  labels:
    app: fdb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fdb
  template:
    metadata:
      labels:
        app: fdb
    spec:
      containers:
        - name: fdb
          image: foundationdb/foundationdb:7.4.5
          env:
            - name: FDB_PORT
              value: "4500"
            - name: FDB_NETWORKING_MODE
              value: host
          ports:
            - containerPort: 4500
          lifecycle:
            postStart:
              exec:
                command:
                  - bash
                  - -c
                  - "until fdbcli --exec 'configure new single memory' 2>/dev/null; do sleep 0.1; done"
          readinessProbe:
            exec:
              command:
                - fdbcli
                - --exec
                - status
            initialDelaySeconds: 5
            periodSeconds: 1
            timeoutSeconds: 5
            failureThreshold: 30
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: alloy
data:
  config.alloy: |
    otelcol.receiver.otlp "default" {
      grpc {
        endpoint = "0.0.0.0:4317"
      }
      output {
        traces  = [otelcol.exporter.otlp.tempo.input]
        logs    = [otelcol.exporter.otlphttp.loki.input]
        metrics = [otelcol.exporter.prometheus.default.input]
      }
    }

    otelcol.exporter.otlp "tempo" {
      client {
        endpoint = "tempo:4317"
        tls {
          insecure = true
        }
      }
    }

    otelcol.exporter.otlphttp "loki" {
      client {
        endpoint = "http://loki:3100/otlp"
      }
    }

    otelcol.exporter.prometheus "default" {
      forward_to = [prometheus.remote_write.default.receiver]
    }

    prometheus.remote_write "default" {
      endpoint {
        url = "http://prometheus:9090/api/v1/write"
      }
    }
---
apiVersion: v1
kind: Service
metadata:
  name: alloy
spec:
  type: LoadBalancer
  selector:
    app: alloy
  ports:
    - name: otlp
      port: 4317
      targetPort: 4317
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: alloy
  labels:
    app: alloy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: alloy
  template:
    metadata:
      labels:
        app: alloy
    spec:
      containers:
        - name: alloy
          image: grafana/alloy:v1.12.2
          args:
            - run
            - /etc/alloy/config.alloy
            - --server.http.listen-addr=0.0.0.0:12345
          ports:
            - containerPort: 4317
            - containerPort: 12345
          volumeMounts:
            - name: config
              mountPath: /etc/alloy
          readinessProbe:
            httpGet:
              path: /-/ready
              port: 12345
            initialDelaySeconds: 5
            periodSeconds: 1
            timeoutSeconds: 5
            failureThreshold: 30
      volumes:
        - name: config
          configMap:
            name: alloy
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: tempo
data:
  tempo.yaml: |
    server:
      http_listen_port: 3200
    distributor:
      receivers:
        otlp:
          protocols:
            grpc:
              endpoint: 0.0.0.0:4317
    storage:
      trace:
        backend: local
        local:
          path: /var/tempo/traces
        wal:
          path: /var/tempo/wal
---
apiVersion: v1
kind: Service
metadata:
  name: tempo
spec:
  selector:
    app: tempo
  ports:
    - name: otlp
      port: 4317
      targetPort: 4317
    - name: http
      port: 3200
      targetPort: 3200
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: tempo
  labels:
    app: tempo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tempo
  template:
    metadata:
      labels:
        app: tempo
    spec:
      containers:
        - name: tempo
          image: grafana/tempo:2.10.0
          args:
            - -config.file=/etc/tempo/tempo.yaml
          ports:
            - containerPort: 4317
            - containerPort: 3200
          volumeMounts:
            - name: config
              mountPath: /etc/tempo
          readinessProbe:
            httpGet:
              path: /ready
              port: 3200
            initialDelaySeconds: 5
            periodSeconds: 1
            timeoutSeconds: 5
            failureThreshold: 30
      volumes:
        - name: config
          configMap:
            name: tempo
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: loki
data:
  loki.yaml: |
    auth_enabled: false
    server:
      http_listen_port: 3100
    common:
      ring:
        instance_addr: 127.0.0.1
        kvstore:
          store: inmemory
      replication_factor: 1
      path_prefix: /loki
    schema_config:
      configs:
        - from: 2024-01-01
          store: tsdb
          object_store: filesystem
          schema: v13
          index:
            prefix: index_
            period: 24h
    storage_config:
      filesystem:
        directory: /loki/chunks
    limits_config:
      allow_structured_metadata: true
---
apiVersion: v1
kind: Service
metadata:
  name: loki
spec:
  selector:
    app: loki
  ports:
    - port: 3100
      targetPort: 3100
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: loki
  labels:
    app: loki
spec:
  replicas: 1
  selector:
    matchLabels:
      app: loki
  template:
    metadata:
      labels:
        app: loki
    spec:
      containers:
        - name: loki
          image: grafana/loki:3.6.4
          args:
            - -config.file=/etc/loki/loki.yaml
          ports:
            - containerPort: 3100
          volumeMounts:
            - name: config
              mountPath: /etc/loki
          readinessProbe:
            httpGet:
              path: /ready
              port: 3100
            initialDelaySeconds: 10
            periodSeconds: 1
            timeoutSeconds: 5
            failureThreshold: 30
      volumes:
        - name: config
          configMap:
            name: loki
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus
data:
  prometheus.yaml: |
    global:
      scrape_interval: 15s
    storage:
      tsdb:
        out_of_order_time_window: 30m
---
apiVersion: v1
kind: Service
metadata:
  name: prometheus
spec:
  selector:
    app: prometheus
  ports:
    - port: 9090
      targetPort: 9090
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: prometheus
  labels:
    app: prometheus
spec:
  replicas: 1
  selector:
    matchLabels:
      app: prometheus
  template:
    metadata:
      labels:
        app: prometheus
    spec:
      containers:
        - name: prometheus
          image: prom/prometheus:v3.9.1
          args:
            - --config.file=/etc/prometheus/prometheus.yaml
            - --web.enable-remote-write-receiver
            - --storage.tsdb.path=/prometheus
          ports:
            - containerPort: 9090
          volumeMounts:
            - name: config
              mountPath: /etc/prometheus
          readinessProbe:
            httpGet:
              path: /-/ready
              port: 9090
            initialDelaySeconds: 5
            periodSeconds: 1
            timeoutSeconds: 5
            failureThreshold: 30
      volumes:
        - name: config
          configMap:
            name: prometheus
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana
data:
  datasources.yaml: |
    apiVersion: 1
    datasources:
      - name: Prometheus
        type: prometheus
        access: proxy
        url: http://prometheus:9090
        isDefault: true
      - name: Tempo
        type: tempo
        access: proxy
        url: http://tempo:3200
      - name: Loki
        type: loki
        access: proxy
        url: http://loki:3100
---
apiVersion: v1
kind: Service
metadata:
  name: grafana
spec:
  type: LoadBalancer
  selector:
    app: grafana
  ports:
    - port: 3000
      targetPort: 3000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: grafana
  labels:
    app: grafana
spec:
  replicas: 1
  selector:
    matchLabels:
      app: grafana
  template:
    metadata:
      labels:
        app: grafana
    spec:
      containers:
        - name: grafana
          image: grafana/grafana:12.3.2
          env:
            - name: GF_AUTH_ANONYMOUS_ENABLED
              value: "true"
            - name: GF_AUTH_ANONYMOUS_ORG_ROLE
              value: Admin
          ports:
            - containerPort: 3000
          volumeMounts:
            - name: datasources
              mountPath: /etc/grafana/provisioning/datasources
          readinessProbe:
            httpGet:
              path: /api/health
              port: 3000
            initialDelaySeconds: 5
            periodSeconds: 1
            timeoutSeconds: 5
            failureThreshold: 30
      volumes:
        - name: datasources
          configMap:
            name: grafana
