apiVersion: v1
kind: Service
metadata:
  name: postgres
spec:
  type: LoadBalancer
  selector:
    app: postgres
  ports:
    - port: 5432
      targetPort: 5432
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
  labels:
    app: postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
        - name: postgres
          image: postgres:18.1
          env:
            - name: POSTGRES_HOST_AUTH_METHOD
              value: trust
          ports:
            - containerPort: 5432
          readinessProbe:
            exec:
              command:
                - pg_isready
                - -U
                - postgres
            initialDelaySeconds: 1
            periodSeconds: 1
            timeoutSeconds: 5
            failureThreshold: 10
---
apiVersion: v1
kind: Service
metadata:
  name: scylla
spec:
  type: LoadBalancer
  selector:
    app: scylla
  ports:
    - port: 9042
      targetPort: 9042
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: scylla
  labels:
    app: scylla
spec:
  replicas: 1
  selector:
    matchLabels:
      app: scylla
  template:
    metadata:
      labels:
        app: scylla
    spec:
      containers:
        - name: scylla
          image: scylladb/scylla:2025.3
          args:
            - --overprovisioned
            - "1"
          ports:
            - containerPort: 9042
          readinessProbe:
            exec:
              command:
                - cqlsh
                - -e
                - DESC KEYSPACES
            initialDelaySeconds: 5
            periodSeconds: 1
            timeoutSeconds: 5
            failureThreshold: 60
---
apiVersion: v1
kind: Service
metadata:
  name: nats
spec:
  type: LoadBalancer
  selector:
    app: nats
  ports:
    - name: client
      port: 4222
      targetPort: 4222
    - name: management
      port: 8222
      targetPort: 8222
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nats
  labels:
    app: nats
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nats
  template:
    metadata:
      labels:
        app: nats
    spec:
      containers:
        - name: nats
          image: nats:2.12
          args:
            - --jetstream
          ports:
            - containerPort: 4222
            - containerPort: 8222
          readinessProbe:
            tcpSocket:
              port: 4222
            initialDelaySeconds: 1
            periodSeconds: 1
            timeoutSeconds: 5
            failureThreshold: 10
---
apiVersion: v1
kind: Service
metadata:
  name: fdb
spec:
  type: LoadBalancer
  selector:
    app: fdb
  ports:
    - port: 4500
      targetPort: 4500
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: fdb
  labels:
    app: fdb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fdb
  template:
    metadata:
      labels:
        app: fdb
    spec:
      containers:
        - name: fdb
          image: foundationdb/foundationdb:7.4.5
          env:
            - name: FDB_PORT
              value: "4500"
            - name: FDB_NETWORKING_MODE
              value: host
          ports:
            - containerPort: 4500
          lifecycle:
            postStart:
              exec:
                command:
                  - bash
                  - -c
                  - "until fdbcli --exec 'configure new single memory' 2>/dev/null; do sleep 0.1; done"
          readinessProbe:
            exec:
              command:
                - fdbcli
                - --exec
                - status
            initialDelaySeconds: 5
            periodSeconds: 1
            timeoutSeconds: 5
            failureThreshold: 30
