/* automatically generated by rust-bindgen 0.72.1 */

#![allow(
	clippy::pub_underscore_fields,
	clippy::unreadable_literal,
	non_camel_case_types,
	non_upper_case_globals
)]

pub const FUSE_KERNEL_VERSION: u32 = 7;
pub const FUSE_KERNEL_MINOR_VERSION: u32 = 45;
pub const FOPEN_KEEP_CACHE: u32 = 2;
pub const FOPEN_CACHE_DIR: u32 = 8;
pub const FOPEN_NOFLUSH: u32 = 32;
pub const FOPEN_PASSTHROUGH: u32 = 128;
pub const FUSE_ASYNC_READ: u32 = 1;
pub const FUSE_SPLICE_MOVE: u32 = 256;
pub const FUSE_SPLICE_READ: u32 = 512;
pub const FUSE_DO_READDIRPLUS: u32 = 8192;
pub const FUSE_READDIRPLUS_AUTO: u32 = 16384;
pub const FUSE_PARALLEL_DIROPS: u32 = 262144;
pub const FUSE_MAX_PAGES: u32 = 4194304;
pub const FUSE_CACHE_SYMLINKS: u32 = 8388608;
pub const FUSE_NO_OPENDIR_SUPPORT: u32 = 16777216;
pub const FUSE_MAP_ALIGNMENT: u32 = 67108864;
pub const FUSE_INIT_EXT: u32 = 1073741824;
pub const FUSE_PASSTHROUGH: u64 = 137438953472;
pub const FUSE_OVER_IO_URING: u64 = 2199023255552;
pub const FUSE_COMPAT_INIT_OUT_SIZE: u32 = 8;
pub const FUSE_COMPAT_22_INIT_OUT_SIZE: u32 = 24;
#[repr(C)]
#[derive(
	Debug, Copy, Clone, zerocopy :: FromBytes, zerocopy :: Immutable, zerocopy :: IntoBytes,
)]
pub struct fuse_attr {
	pub ino: u64,
	pub size: u64,
	pub blocks: u64,
	pub atime: u64,
	pub mtime: u64,
	pub ctime: u64,
	pub atimensec: u32,
	pub mtimensec: u32,
	pub ctimensec: u32,
	pub mode: u32,
	pub nlink: u32,
	pub uid: u32,
	pub gid: u32,
	pub rdev: u32,
	pub blksize: u32,
	pub flags: u32,
}
#[repr(C)]
#[derive(
	Debug, Copy, Clone, zerocopy :: FromBytes, zerocopy :: Immutable, zerocopy :: IntoBytes,
)]
pub struct fuse_sx_time {
	pub tv_sec: i64,
	pub tv_nsec: u32,
	pub __reserved: i32,
}
#[repr(C)]
#[derive(
	Debug, Copy, Clone, zerocopy :: FromBytes, zerocopy :: Immutable, zerocopy :: IntoBytes,
)]
pub struct fuse_statx {
	pub mask: u32,
	pub blksize: u32,
	pub attributes: u64,
	pub nlink: u32,
	pub uid: u32,
	pub gid: u32,
	pub mode: u16,
	pub __spare0: [u16; 1usize],
	pub ino: u64,
	pub size: u64,
	pub blocks: u64,
	pub attributes_mask: u64,
	pub atime: fuse_sx_time,
	pub btime: fuse_sx_time,
	pub ctime: fuse_sx_time,
	pub mtime: fuse_sx_time,
	pub rdev_major: u32,
	pub rdev_minor: u32,
	pub dev_major: u32,
	pub dev_minor: u32,
	pub __spare2: [u64; 14usize],
}
#[repr(C)]
#[derive(
	Debug, Copy, Clone, zerocopy :: FromBytes, zerocopy :: Immutable, zerocopy :: IntoBytes,
)]
pub struct fuse_kstatfs {
	pub blocks: u64,
	pub bfree: u64,
	pub bavail: u64,
	pub files: u64,
	pub ffree: u64,
	pub bsize: u32,
	pub namelen: u32,
	pub frsize: u32,
	pub padding: u32,
	pub spare: [u32; 6usize],
}
pub const fuse_opcode_FUSE_LOOKUP: fuse_opcode = 1;
pub const fuse_opcode_FUSE_FORGET: fuse_opcode = 2;
pub const fuse_opcode_FUSE_GETATTR: fuse_opcode = 3;
pub const fuse_opcode_FUSE_SETATTR: fuse_opcode = 4;
pub const fuse_opcode_FUSE_READLINK: fuse_opcode = 5;
pub const fuse_opcode_FUSE_SYMLINK: fuse_opcode = 6;
pub const fuse_opcode_FUSE_MKNOD: fuse_opcode = 8;
pub const fuse_opcode_FUSE_MKDIR: fuse_opcode = 9;
pub const fuse_opcode_FUSE_UNLINK: fuse_opcode = 10;
pub const fuse_opcode_FUSE_RMDIR: fuse_opcode = 11;
pub const fuse_opcode_FUSE_RENAME: fuse_opcode = 12;
pub const fuse_opcode_FUSE_LINK: fuse_opcode = 13;
pub const fuse_opcode_FUSE_OPEN: fuse_opcode = 14;
pub const fuse_opcode_FUSE_READ: fuse_opcode = 15;
pub const fuse_opcode_FUSE_WRITE: fuse_opcode = 16;
pub const fuse_opcode_FUSE_STATFS: fuse_opcode = 17;
pub const fuse_opcode_FUSE_RELEASE: fuse_opcode = 18;
pub const fuse_opcode_FUSE_FSYNC: fuse_opcode = 20;
pub const fuse_opcode_FUSE_SETXATTR: fuse_opcode = 21;
pub const fuse_opcode_FUSE_GETXATTR: fuse_opcode = 22;
pub const fuse_opcode_FUSE_LISTXATTR: fuse_opcode = 23;
pub const fuse_opcode_FUSE_REMOVEXATTR: fuse_opcode = 24;
pub const fuse_opcode_FUSE_FLUSH: fuse_opcode = 25;
pub const fuse_opcode_FUSE_INIT: fuse_opcode = 26;
pub const fuse_opcode_FUSE_OPENDIR: fuse_opcode = 27;
pub const fuse_opcode_FUSE_READDIR: fuse_opcode = 28;
pub const fuse_opcode_FUSE_RELEASEDIR: fuse_opcode = 29;
pub const fuse_opcode_FUSE_FSYNCDIR: fuse_opcode = 30;
pub const fuse_opcode_FUSE_GETLK: fuse_opcode = 31;
pub const fuse_opcode_FUSE_SETLK: fuse_opcode = 32;
pub const fuse_opcode_FUSE_SETLKW: fuse_opcode = 33;
pub const fuse_opcode_FUSE_ACCESS: fuse_opcode = 34;
pub const fuse_opcode_FUSE_CREATE: fuse_opcode = 35;
pub const fuse_opcode_FUSE_INTERRUPT: fuse_opcode = 36;
pub const fuse_opcode_FUSE_BMAP: fuse_opcode = 37;
pub const fuse_opcode_FUSE_DESTROY: fuse_opcode = 38;
pub const fuse_opcode_FUSE_IOCTL: fuse_opcode = 39;
pub const fuse_opcode_FUSE_POLL: fuse_opcode = 40;
pub const fuse_opcode_FUSE_NOTIFY_REPLY: fuse_opcode = 41;
pub const fuse_opcode_FUSE_BATCH_FORGET: fuse_opcode = 42;
pub const fuse_opcode_FUSE_FALLOCATE: fuse_opcode = 43;
pub const fuse_opcode_FUSE_READDIRPLUS: fuse_opcode = 44;
pub const fuse_opcode_FUSE_RENAME2: fuse_opcode = 45;
pub const fuse_opcode_FUSE_LSEEK: fuse_opcode = 46;
pub const fuse_opcode_FUSE_COPY_FILE_RANGE: fuse_opcode = 47;
pub const fuse_opcode_FUSE_SETUPMAPPING: fuse_opcode = 48;
pub const fuse_opcode_FUSE_REMOVEMAPPING: fuse_opcode = 49;
pub const fuse_opcode_FUSE_SYNCFS: fuse_opcode = 50;
pub const fuse_opcode_FUSE_TMPFILE: fuse_opcode = 51;
pub const fuse_opcode_FUSE_STATX: fuse_opcode = 52;
pub const fuse_opcode_FUSE_COPY_FILE_RANGE_64: fuse_opcode = 53;
pub const fuse_opcode_CUSE_INIT: fuse_opcode = 4096;
pub const fuse_opcode_CUSE_INIT_BSWAP_RESERVED: fuse_opcode = 1048576;
pub const fuse_opcode_FUSE_INIT_BSWAP_RESERVED: fuse_opcode = 436207616;
pub type fuse_opcode = ::std::os::raw::c_uint;
#[repr(C)]
#[derive(
	Debug, Copy, Clone, zerocopy :: FromBytes, zerocopy :: Immutable, zerocopy :: IntoBytes,
)]
pub struct fuse_entry_out {
	pub nodeid: u64,
	pub generation: u64,
	pub entry_valid: u64,
	pub attr_valid: u64,
	pub entry_valid_nsec: u32,
	pub attr_valid_nsec: u32,
	pub attr: fuse_attr,
}
#[repr(C)]
#[derive(
	Debug, Copy, Clone, zerocopy :: FromBytes, zerocopy :: Immutable, zerocopy :: IntoBytes,
)]
pub struct fuse_forget_in {
	pub nlookup: u64,
}
#[repr(C)]
#[derive(
	Debug, Copy, Clone, zerocopy :: FromBytes, zerocopy :: Immutable, zerocopy :: IntoBytes,
)]
pub struct fuse_forget_one {
	pub nodeid: u64,
	pub nlookup: u64,
}
#[repr(C)]
#[derive(
	Debug, Copy, Clone, zerocopy :: FromBytes, zerocopy :: Immutable, zerocopy :: IntoBytes,
)]
pub struct fuse_batch_forget_in {
	pub count: u32,
	pub dummy: u32,
}
#[repr(C)]
#[derive(
	Debug, Copy, Clone, zerocopy :: FromBytes, zerocopy :: Immutable, zerocopy :: IntoBytes,
)]
pub struct fuse_getattr_in {
	pub getattr_flags: u32,
	pub dummy: u32,
	pub fh: u64,
}
#[repr(C)]
#[derive(
	Debug, Copy, Clone, zerocopy :: FromBytes, zerocopy :: Immutable, zerocopy :: IntoBytes,
)]
pub struct fuse_attr_out {
	pub attr_valid: u64,
	pub attr_valid_nsec: u32,
	pub dummy: u32,
	pub attr: fuse_attr,
}
#[repr(C)]
#[derive(
	Debug, Copy, Clone, zerocopy :: FromBytes, zerocopy :: Immutable, zerocopy :: IntoBytes,
)]
pub struct fuse_statx_in {
	pub getattr_flags: u32,
	pub reserved: u32,
	pub fh: u64,
	pub sx_flags: u32,
	pub sx_mask: u32,
}
#[repr(C)]
#[derive(
	Debug, Copy, Clone, zerocopy :: FromBytes, zerocopy :: Immutable, zerocopy :: IntoBytes,
)]
pub struct fuse_statx_out {
	pub attr_valid: u64,
	pub attr_valid_nsec: u32,
	pub flags: u32,
	pub spare: [u64; 2usize],
	pub stat: fuse_statx,
}
#[repr(C)]
#[derive(
	Debug, Copy, Clone, zerocopy :: FromBytes, zerocopy :: Immutable, zerocopy :: IntoBytes,
)]
pub struct fuse_open_in {
	pub flags: u32,
	pub open_flags: u32,
}
#[repr(C)]
#[derive(
	Debug, Copy, Clone, zerocopy :: FromBytes, zerocopy :: Immutable, zerocopy :: IntoBytes,
)]
pub struct fuse_open_out {
	pub fh: u64,
	pub open_flags: u32,
	pub backing_id: i32,
}
#[repr(C)]
#[derive(
	Debug, Copy, Clone, zerocopy :: FromBytes, zerocopy :: Immutable, zerocopy :: IntoBytes,
)]
pub struct fuse_release_in {
	pub fh: u64,
	pub flags: u32,
	pub release_flags: u32,
	pub lock_owner: u64,
}
#[repr(C)]
#[derive(
	Debug, Copy, Clone, zerocopy :: FromBytes, zerocopy :: Immutable, zerocopy :: IntoBytes,
)]
pub struct fuse_flush_in {
	pub fh: u64,
	pub unused: u32,
	pub padding: u32,
	pub lock_owner: u64,
}
#[repr(C)]
#[derive(
	Debug, Copy, Clone, zerocopy :: FromBytes, zerocopy :: Immutable, zerocopy :: IntoBytes,
)]
pub struct fuse_read_in {
	pub fh: u64,
	pub offset: u64,
	pub size: u32,
	pub read_flags: u32,
	pub lock_owner: u64,
	pub flags: u32,
	pub padding: u32,
}
#[repr(C)]
#[derive(
	Debug, Copy, Clone, zerocopy :: FromBytes, zerocopy :: Immutable, zerocopy :: IntoBytes,
)]
pub struct fuse_statfs_out {
	pub st: fuse_kstatfs,
}
#[repr(C)]
#[derive(
	Debug, Copy, Clone, zerocopy :: FromBytes, zerocopy :: Immutable, zerocopy :: IntoBytes,
)]
pub struct fuse_getxattr_in {
	pub size: u32,
	pub padding: u32,
}
#[repr(C)]
#[derive(
	Debug, Copy, Clone, zerocopy :: FromBytes, zerocopy :: Immutable, zerocopy :: IntoBytes,
)]
pub struct fuse_getxattr_out {
	pub size: u32,
	pub padding: u32,
}
#[repr(C)]
#[derive(
	Debug, Copy, Clone, zerocopy :: FromBytes, zerocopy :: Immutable, zerocopy :: IntoBytes,
)]
pub struct fuse_init_in {
	pub major: u32,
	pub minor: u32,
	pub max_readahead: u32,
	pub flags: u32,
	pub flags2: u32,
	pub unused: [u32; 11usize],
}
#[repr(C)]
#[derive(
	Debug, Copy, Clone, zerocopy :: FromBytes, zerocopy :: Immutable, zerocopy :: IntoBytes,
)]
pub struct fuse_init_out {
	pub major: u32,
	pub minor: u32,
	pub max_readahead: u32,
	pub flags: u32,
	pub max_background: u16,
	pub congestion_threshold: u16,
	pub max_write: u32,
	pub time_gran: u32,
	pub max_pages: u16,
	pub map_alignment: u16,
	pub flags2: u32,
	pub max_stack_depth: u32,
	pub request_timeout: u16,
	pub unused: [u16; 11usize],
}
#[repr(C)]
#[derive(
	Debug, Copy, Clone, zerocopy :: FromBytes, zerocopy :: Immutable, zerocopy :: IntoBytes,
)]
pub struct fuse_interrupt_in {
	pub unique: u64,
}
#[repr(C)]
#[derive(
	Debug, Copy, Clone, zerocopy :: FromBytes, zerocopy :: Immutable, zerocopy :: IntoBytes,
)]
pub struct fuse_in_header {
	pub len: u32,
	pub opcode: u32,
	pub unique: u64,
	pub nodeid: u64,
	pub uid: u32,
	pub gid: u32,
	pub pid: u32,
	pub total_extlen: u16,
	pub padding: u16,
}
#[repr(C)]
#[derive(
	Debug, Copy, Clone, zerocopy :: FromBytes, zerocopy :: Immutable, zerocopy :: IntoBytes,
)]
pub struct fuse_out_header {
	pub len: u32,
	pub error: i32,
	pub unique: u64,
}
#[repr(C)]
#[derive(
	Debug, Copy, Clone, zerocopy :: FromBytes, zerocopy :: Immutable, zerocopy :: IntoBytes,
)]
pub struct fuse_backing_map {
	pub fd: i32,
	pub flags: u32,
	pub padding: u64,
}
#[repr(C)]
#[derive(
	Debug, Copy, Clone, zerocopy :: FromBytes, zerocopy :: Immutable, zerocopy :: IntoBytes,
)]
pub struct fuse_uring_ent_in_out {
	pub flags: u64,
	pub commit_id: u64,
	pub payload_sz: u32,
	pub padding: u32,
	pub reserved: u64,
}
#[repr(C)]
#[derive(
	Debug, Copy, Clone, zerocopy :: FromBytes, zerocopy :: Immutable, zerocopy :: IntoBytes,
)]
pub struct fuse_uring_req_header {
	pub in_out: [::std::os::raw::c_char; 128usize],
	pub op_in: [::std::os::raw::c_char; 128usize],
	pub ring_ent_in_out: fuse_uring_ent_in_out,
}
pub const fuse_uring_cmd_FUSE_IO_URING_CMD_INVALID: fuse_uring_cmd = 0;
pub const fuse_uring_cmd_FUSE_IO_URING_CMD_REGISTER: fuse_uring_cmd = 1;
pub const fuse_uring_cmd_FUSE_IO_URING_CMD_COMMIT_AND_FETCH: fuse_uring_cmd = 2;
pub type fuse_uring_cmd = ::std::os::raw::c_uint;
#[repr(C)]
#[derive(
	Debug, Copy, Clone, zerocopy :: FromBytes, zerocopy :: Immutable, zerocopy :: IntoBytes,
)]
pub struct fuse_uring_cmd_req {
	pub flags: u64,
	pub commit_id: u64,
	pub qid: u16,
	pub padding: [u8; 6usize],
}
